package com.irc.model;
// Generated 2 Oct, 2017 8:28:59 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Passenger generated by hbm2java
 */
@Entity
@Table(name = "PASSENGER", schema = "INDIAN_RAILWAYS")
public class Passenger implements java.io.Serializable {

	private short passengerId;
	private PassengerAddress passengerAddress;
	private String passengerName;
	private String gender;
	private Short age;
	private String password;
	private Set<PassengerBookingDetails> passengerBookingDetailses = new HashSet<PassengerBookingDetails>(0);
	private Set<PnrStatus> pnrStatuses = new HashSet<PnrStatus>(0);

	public Passenger() {
	}

	public Passenger(short passengerId, String password) {
		this.passengerId = passengerId;
		this.password = password;
	}

	public Passenger(short passengerId, PassengerAddress passengerAddress, String passengerName, String gender,
			Short age, String password, Set<PassengerBookingDetails> passengerBookingDetailses,
			Set<PnrStatus> pnrStatuses) {
		this.passengerId = passengerId;
		this.passengerAddress = passengerAddress;
		this.passengerName = passengerName;
		this.gender = gender;
		this.age = age;
		this.password = password;
		this.passengerBookingDetailses = passengerBookingDetailses;
		this.pnrStatuses = pnrStatuses;
	}

	@Id

	@Column(name = "PASSENGER_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getPassengerId() {
		return this.passengerId;
	}

	public void setPassengerId(short passengerId) {
		this.passengerId = passengerId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PASSENGER_ADDRESS_ID")
	public PassengerAddress getPassengerAddress() {
		return this.passengerAddress;
	}

	public void setPassengerAddress(PassengerAddress passengerAddress) {
		this.passengerAddress = passengerAddress;
	}

	@Column(name = "PASSENGER_NAME", length = 30)
	public String getPassengerName() {
		return this.passengerName;
	}

	public void setPassengerName(String passengerName) {
		this.passengerName = passengerName;
	}

	@Column(name = "GENDER", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "AGE", precision = 4, scale = 0)
	public Short getAge() {
		return this.age;
	}

	public void setAge(Short age) {
		this.age = age;
	}

	@Column(name = "PASSWORD", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passenger")
	public Set<PassengerBookingDetails> getPassengerBookingDetailses() {
		return this.passengerBookingDetailses;
	}

	public void setPassengerBookingDetailses(Set<PassengerBookingDetails> passengerBookingDetailses) {
		this.passengerBookingDetailses = passengerBookingDetailses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passenger")
	public Set<PnrStatus> getPnrStatuses() {
		return this.pnrStatuses;
	}

	public void setPnrStatuses(Set<PnrStatus> pnrStatuses) {
		this.pnrStatuses = pnrStatuses;
	}

}
