package com.irc.entity;
// Generated 1 Nov, 2017 9:28:38 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "BOOKING", schema = "INDIAN_RAILWAYS")
public class Booking implements java.io.Serializable {

	private int bookingId;
	private Train train;
	private Coach coach;
	private Short seatNo;
	private String sourceStn;
	private String destinationStn;
	private Date dateOfJourney;
	private Date dateOfBooking;
	private String seatConfirmed;
	private Long pnrNo;

	public Booking() {
	}

	public Booking(int bookingId, Train train) {
		this.bookingId = bookingId;
		this.train = train;
	}

	public Booking(int bookingId, Train train, Coach coach, Short seatNo, String sourceStn, String destinationStn,
			Date dateOfJourney, Date dateOfBooking, String seatConfirmed, Long pnrNo) {
		this.bookingId = bookingId;
		this.train = train;
		this.coach = coach;
		this.seatNo = seatNo;
		this.sourceStn = sourceStn;
		this.destinationStn = destinationStn;
		this.dateOfJourney = dateOfJourney;
		this.dateOfBooking = dateOfBooking;
		this.seatConfirmed = seatConfirmed;
		this.pnrNo = pnrNo;
	}

	@Id

	@Column(name = "BOOKING_ID", unique = true, nullable = false, precision = 8, scale = 0)
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAIN_ID", nullable = false)
	public Train getTrain() {
		return this.train;
	}

	public void setTrain(Train train) {
		this.train = train;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COACH_ID")
	public Coach getCoach() {
		return this.coach;
	}

	public void setCoach(Coach coach) {
		this.coach = coach;
	}

	@Column(name = "SEAT_NO", precision = 4, scale = 0)
	public Short getSeatNo() {
		return this.seatNo;
	}

	public void setSeatNo(Short seatNo) {
		this.seatNo = seatNo;
	}

	@Column(name = "SOURCE_STN", length = 30)
	public String getSourceStn() {
		return this.sourceStn;
	}

	public void setSourceStn(String sourceStn) {
		this.sourceStn = sourceStn;
	}

	@Column(name = "DESTINATION_STN", length = 30)
	public String getDestinationStn() {
		return this.destinationStn;
	}

	public void setDestinationStn(String destinationStn) {
		this.destinationStn = destinationStn;
	}

	@Column(name = "DATE_OF_JOURNEY")
	public Date getDateOfJourney() {
		return this.dateOfJourney;
	}

	public void setDateOfJourney(Date dateOfJourney) {
		this.dateOfJourney = dateOfJourney;
	}

	@Column(name = "DATE_OF_BOOKING")
	public Date getDateOfBooking() {
		return this.dateOfBooking;
	}

	public void setDateOfBooking(Date dateOfBooking) {
		this.dateOfBooking = dateOfBooking;
	}

	@Column(name = "SEAT_CONFIRMED", length = 5)
	public String getSeatConfirmed() {
		return this.seatConfirmed;
	}

	public void setSeatConfirmed(String seatConfirmed) {
		this.seatConfirmed = seatConfirmed;
	}

	@Column(name = "PNR_NO", precision = 10, scale = 0)
	public Long getPnrNo() {
		return this.pnrNo;
	}

	public void setPnrNo(Long pnrNo) {
		this.pnrNo = pnrNo;
	}

}
