package com.irc.entity;
// Generated 3 Nov, 2017 10:44:37 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Booking generated by hbm2java
 */
@Entity
@Table(name = "BOOKING", schema = "INDIAN_RAILWAYS")
public class Booking implements java.io.Serializable {

	private int bookingId;
	private Route route;
	private Train train;
	private Coach coach;
	private Short seatNo;
	private Date dateOfJourney;
	private Date dateOfBooking;
	private String sourceStn;
	private Date sourceStnArrTime;
	private String destinationStn;
	private Date destinationStnArrTime;
	private String seatConfirmed;
	private Long pnrNo;

	public Booking() {
	}

	public Booking(int bookingId) {
		this.bookingId = bookingId;
	}

	public Booking(int bookingId, Route route, Train train, Coach coach, Short seatNo, Date dateOfJourney,
			Date dateOfBooking, String sourceStn, Date sourceStnArrTime, String destinationStn,
			Date destinationStnArrTime, String seatConfirmed, Long pnrNo) {
		this.bookingId = bookingId;
		this.route = route;
		this.train = train;
		this.coach = coach;
		this.seatNo = seatNo;
		this.dateOfJourney = dateOfJourney;
		this.dateOfBooking = dateOfBooking;
		this.sourceStn = sourceStn;
		this.sourceStnArrTime = sourceStnArrTime;
		this.destinationStn = destinationStn;
		this.destinationStnArrTime = destinationStnArrTime;
		this.seatConfirmed = seatConfirmed;
		this.pnrNo = pnrNo;
	}

	@Id

	@Column(name = "BOOKING_ID", unique = true, nullable = false, precision = 8, scale = 0)
	@SequenceGenerator(sequenceName="BOOKING_SEQ",name="bookingSeq",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="bookingSeq")
	public int getBookingId() {
		return this.bookingId;
	}

	public void setBookingId(int bookingId) {
		this.bookingId = bookingId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ROUTE_ID")
	@JsonBackReference
	public Route getRoute() {
		return this.route;
	}

	public void setRoute(Route route) {
		this.route = route;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAIN_ID")
	@JsonBackReference
	public Train getTrain() {
		return this.train;
	}

	public void setTrain(Train train) {
		this.train = train;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COACH_ID")
	@JsonBackReference
	public Coach getCoach() {
		return this.coach;
	}

	public void setCoach(Coach coach) {
		this.coach = coach;
	}

	@Column(name = "SEAT_NO", precision = 4, scale = 0)
	public Short getSeatNo() {
		return this.seatNo;
	}

	public void setSeatNo(Short seatNo) {
		this.seatNo = seatNo;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_OF_JOURNEY", length = 7)
	public Date getDateOfJourney() {
		return this.dateOfJourney;
	}

	public void setDateOfJourney(Date dateOfJourney) {
		this.dateOfJourney = dateOfJourney;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_OF_BOOKING", length = 7)
	public Date getDateOfBooking() {
		return this.dateOfBooking;
	}

	public void setDateOfBooking(Date dateOfBooking) {
		this.dateOfBooking = dateOfBooking;
	}

	@Column(name = "SOURCE_STN", length = 30)
	public String getSourceStn() {
		return this.sourceStn;
	}

	public void setSourceStn(String sourceStn) {
		this.sourceStn = sourceStn;
	}

	@Column(name = "SOURCE_STN_ARR_TIME")
	public Date getSourceStnArrTime() {
		return this.sourceStnArrTime;
	}

	public void setSourceStnArrTime(Date sourceStnArrTime) {
		this.sourceStnArrTime = sourceStnArrTime;
	}

	@Column(name = "DESTINATION_STN", length = 30)
	public String getDestinationStn() {
		return this.destinationStn;
	}

	public void setDestinationStn(String destinationStn) {
		this.destinationStn = destinationStn;
	}

	@Column(name = "DESTINATION_STN_ARR_TIME")
	public Date getDestinationStnArrTime() {
		return this.destinationStnArrTime;
	}

	public void setDestinationStnArrTime(Date destinationStnArrTime) {
		this.destinationStnArrTime = destinationStnArrTime;
	}

	@Column(name = "SEAT_CONFIRMED", length = 5)
	public String getSeatConfirmed() {
		return this.seatConfirmed;
	}

	public void setSeatConfirmed(String seatConfirmed) {
		this.seatConfirmed = seatConfirmed;
	}

	@Column(name = "PNR_NO", precision = 10, scale = 0)
	public Long getPnrNo() {
		return this.pnrNo;
	}

	public void setPnrNo(Long pnrNo) {
		this.pnrNo = pnrNo;
	}

}
