package com.irc.entity;
// Generated 3 Nov, 2017 10:44:37 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CoachType generated by hbm2java
 */
@Entity
@Table(name = "COACH_TYPE", schema = "INDIAN_RAILWAYS")
public class CoachType implements java.io.Serializable {

	private short coachTypeId;
	private String coachType;
	private String coachTypeAcronym;
	private Short seatCapacity;
	private Set<Coach> coaches = new HashSet<Coach>(0);

	public CoachType() {
	}

	public CoachType(short coachTypeId, String coachType, String coachTypeAcronym, Short seatCapacity) {
		this.coachTypeId = coachTypeId;
		this.coachType = coachType;
		this.coachTypeAcronym = coachTypeAcronym;
		this.seatCapacity = seatCapacity;
	}

	public CoachType(short coachTypeId, String coachType, String coachTypeAcronym, Short seatCapacity,
			Set<Coach> coaches) {
		this.coachTypeId = coachTypeId;
		this.coachType = coachType;
		this.coachTypeAcronym = coachTypeAcronym;
		this.seatCapacity = seatCapacity;
		this.coaches = coaches;
	}

	@Id

	@Column(name = "COACH_TYPE_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getCoachTypeId() {
		return this.coachTypeId;
	}

	public void setCoachTypeId(short coachTypeId) {
		this.coachTypeId = coachTypeId;
	}

	@Column(name = "COACH_TYPE", nullable = false, length = 15)
	public String getCoachType() {
		return this.coachType;
	}

	public void setCoachType(String coachType) {
		this.coachType = coachType;
	}

	@Column(name = "COACH_TYPE_ACRONYM", nullable = false, length = 30)
	public String getCoachTypeAcronym() {
		return this.coachTypeAcronym;
	}

	public void setCoachTypeAcronym(String coachTypeAcronym) {
		this.coachTypeAcronym = coachTypeAcronym;
	}

	@Column(name = "SEAT_CAPACITY", nullable = false, precision = 22, scale = 0)
	public Short getSeatCapacity() {
		return this.seatCapacity;
	}

	public void setSeatCapacity(Short seatCapacity) {
		this.seatCapacity = seatCapacity;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coachType")
	public Set<Coach> getCoaches() {
		return this.coaches;
	}

	public void setCoaches(Set<Coach> coaches) {
		this.coaches = coaches;
	}

}
