package com.irc.entity;
// Generated 8 Oct, 2017 4:43:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Coach generated by hbm2java
 */
@Entity
@Table(name = "COACH", schema = "INDIAN_RAILWAYS")
public class Coach implements java.io.Serializable {

	private short coachId;
	private CoachType coachType;
	private Set<TrainCoachSeatBooking> trainCoachSeatBookings = new HashSet<TrainCoachSeatBooking>(0);
	private Set<TrainCoaches> trainCoacheses = new HashSet<TrainCoaches>(0);

	public Coach() {
	}

	public Coach(short coachId) {
		this.coachId = coachId;
	}

	public Coach(short coachId, CoachType coachType, Set<TrainCoachSeatBooking> trainCoachSeatBookings,
			Set<TrainCoaches> trainCoacheses) {
		this.coachId = coachId;
		this.coachType = coachType;
		this.trainCoachSeatBookings = trainCoachSeatBookings;
		this.trainCoacheses = trainCoacheses;
	}

	@Id

	@Column(name = "COACH_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getCoachId() {
		return this.coachId;
	}

	public void setCoachId(short coachId) {
		this.coachId = coachId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COACH_TYPE_ID")
	public CoachType getCoachType() {
		return this.coachType;
	}

	public void setCoachType(CoachType coachType) {
		this.coachType = coachType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coach")
	public Set<TrainCoachSeatBooking> getTrainCoachSeatBookings() {
		return this.trainCoachSeatBookings;
	}

	public void setTrainCoachSeatBookings(Set<TrainCoachSeatBooking> trainCoachSeatBookings) {
		this.trainCoachSeatBookings = trainCoachSeatBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coach")
	public Set<TrainCoaches> getTrainCoacheses() {
		return this.trainCoacheses;
	}

	public void setTrainCoacheses(Set<TrainCoaches> trainCoacheses) {
		this.trainCoacheses = trainCoacheses;
	}

}
