package com.irc.entity;
// Generated 8 Oct, 2017 4:43:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CoachType generated by hbm2java
 */
@Entity
@Table(name = "COACH_TYPE", schema = "INDIAN_RAILWAYS")
public class CoachType implements java.io.Serializable {

	private short coachTypeId;
	private String coachType;
	private Short coachSeats;
	private Set<Coach> coaches = new HashSet<Coach>(0);

	public CoachType() {
	}

	public CoachType(short coachTypeId) {
		this.coachTypeId = coachTypeId;
	}

	public CoachType(short coachTypeId, String coachType, Short coachSeats, Set<Coach> coaches) {
		this.coachTypeId = coachTypeId;
		this.coachType = coachType;
		this.coachSeats = coachSeats;
		this.coaches = coaches;
	}

	@Id

	@Column(name = "COACH_TYPE_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getCoachTypeId() {
		return this.coachTypeId;
	}

	public void setCoachTypeId(short coachTypeId) {
		this.coachTypeId = coachTypeId;
	}

	@Column(name = "COACH_TYPE", length = 15)
	public String getCoachType() {
		return this.coachType;
	}

	public void setCoachType(String coachType) {
		this.coachType = coachType;
	}

	@Column(name = "COACH_SEATS", precision = 4, scale = 0)
	public Short getCoachSeats() {
		return this.coachSeats;
	}

	public void setCoachSeats(Short coachSeats) {
		this.coachSeats = coachSeats;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coachType")
	public Set<Coach> getCoaches() {
		return this.coaches;
	}

	public void setCoaches(Set<Coach> coaches) {
		this.coaches = coaches;
	}

}
