package com.irc.entity;
// Generated 3 Nov, 2017 10:44:37 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;

/**
 * Coach generated by hbm2java
 */
@Entity
@Table(name = "COACH", schema = "INDIAN_RAILWAYS")
public class Coach implements java.io.Serializable {

	private short coachId;
	private Train train;
	private CoachType coachType;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Coach() {
	}

	public Coach(short coachId, Train train, CoachType coachType) {
		this.coachId = coachId;
		this.train = train;
		this.coachType = coachType;
	}

	public Coach(short coachId, Train train, CoachType coachType, Set<Booking> bookings) {
		this.coachId = coachId;
		this.train = train;
		this.coachType = coachType;
		this.bookings = bookings;
	}

	@Id

	@Column(name = "COACH_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getCoachId() {
		return this.coachId;
	}

	public void setCoachId(short coachId) {
		this.coachId = coachId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAIN_ID", nullable = false)
	@JsonManagedReference
	public Train getTrain() {
		return this.train;
	}

	public void setTrain(Train train) {
		this.train = train;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COACH_TYPE_ID", nullable = false)
	@JsonManagedReference
	public CoachType getCoachType() {
		return this.coachType;
	}

	public void setCoachType(CoachType coachType) {
		this.coachType = coachType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "coach")
	@JsonBackReference
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
