package com.irc.entity;
// Generated 1 Nov, 2017 9:28:38 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.Cascade;

/**
 * Passenger generated by hbm2java
 */
@Entity
@Table(name = "PASSENGER", schema = "INDIAN_RAILWAYS")
public class Passenger implements java.io.Serializable {

	private String passengerId;
	private PassengerAddress passengerAddress;
	private String passengerName;
	private String gender;
	private Short age;
	private String password;
	private Set<PassengerBookingHistory> passengerBookingHistories = new HashSet<PassengerBookingHistory>(0);
	private Set<PnrStatus> pnrStatuses = new HashSet<PnrStatus>(0);

	public Passenger() {
	}

	public Passenger(String passengerId, String password) {
		this.passengerId = passengerId;
		this.password = password;
	}

	public Passenger(String passengerId, PassengerAddress passengerAddress, String passengerName, String gender,
			Short age, String password, Set<PassengerBookingHistory> passengerBookingHistories,
			Set<PnrStatus> pnrStatuses) {
		this.passengerId = passengerId;
		this.passengerAddress = passengerAddress;
		this.passengerName = passengerName;
		this.gender = gender;
		this.age = age;
		this.password = password;
		this.passengerBookingHistories = passengerBookingHistories;
		this.pnrStatuses = pnrStatuses;
	}

	@Id

	@Column(name = "PASSENGER_ID", unique = true, nullable = false, length = 30)
	public String getPassengerId() {
		return this.passengerId;
	}

	public void setPassengerId(String passengerId) {
		this.passengerId = passengerId;
	}

	@ManyToOne(fetch = FetchType.LAZY,cascade=CascadeType.ALL)
	@JoinColumn(name = "PASSENGER_ADDRESS_ID")
	public PassengerAddress getPassengerAddress() {
		return this.passengerAddress;
	}

	public void setPassengerAddress(PassengerAddress passengerAddress) {
		this.passengerAddress = passengerAddress;
	}

	@Column(name = "PASSENGER_NAME", length = 30)
	public String getPassengerName() {
		return this.passengerName;
	}

	public void setPassengerName(String passengerName) {
		this.passengerName = passengerName;
	}

	@Column(name = "GENDER", length = 10)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Column(name = "AGE", precision = 4, scale = 0)
	public Short getAge() {
		return this.age;
	}

	public void setAge(Short age) {
		this.age = age;
	}

	@Column(name = "PASSWORD", nullable = false, length = 15)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passenger")
	public Set<PassengerBookingHistory> getPassengerBookingHistories() {
		return this.passengerBookingHistories;
	}

	public void setPassengerBookingHistories(Set<PassengerBookingHistory> passengerBookingHistories) {
		this.passengerBookingHistories = passengerBookingHistories;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "passenger")
	public Set<PnrStatus> getPnrStatuses() {
		return this.pnrStatuses;
	}

	public void setPnrStatuses(Set<PnrStatus> pnrStatuses) {
		this.pnrStatuses = pnrStatuses;
	}

}
