package com.irc.entity;
// Generated 3 Nov, 2017 10:44:37 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * PassengerBookingHistory generated by hbm2java
 */
@Entity
@Table(name = "PASSENGER_BOOKING_HISTORY", schema = "INDIAN_RAILWAYS")
public class PassengerBookingHistory implements java.io.Serializable {

	private short psngrBkgId;
	private Passenger passenger;
	private Long pnrNo;

	public PassengerBookingHistory() {
	}

	public PassengerBookingHistory(short psngrBkgId) {
		this.psngrBkgId = psngrBkgId;
	}

	public PassengerBookingHistory(short psngrBkgId, Passenger passenger, Long pnrNo) {
		this.psngrBkgId = psngrBkgId;
		this.passenger = passenger;
		this.pnrNo = pnrNo;
	}

	@Id
	@Column(name = "PSNGR_BKG_ID", unique = true, nullable = false, precision = 4, scale = 0)
	@SequenceGenerator(sequenceName="INDIAN_RAILWAYS.PSNGER_BOOKING_HIS_SEQ",name="passengerHisSeq",allocationSize=1)
	@GeneratedValue(strategy=GenerationType.SEQUENCE,generator="passengerHisSeq")
	public short getPsngrBkgId() {
		return this.psngrBkgId;
	}

	public void setPsngrBkgId(short psngrBkgId) {
		this.psngrBkgId = psngrBkgId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PSNGR_ID")
	public Passenger getPassenger() {
		return this.passenger;
	}

	public void setPassenger(Passenger passenger) {
		this.passenger = passenger;
	}

	@Column(name = "PNR_NO", precision = 15, scale = 0)
	public Long getPnrNo() {
		return this.pnrNo;
	}

	public void setPnrNo(Long pnrNo) {
		this.pnrNo = pnrNo;
	}

}
