package com.irc.entity;
// Generated 1 Nov, 2017 9:28:38 AM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PnrStatus generated by hbm2java
 */
@Entity
@Table(name = "PNR_STATUS", schema = "INDIAN_RAILWAYS", uniqueConstraints = @UniqueConstraint(columnNames = "PNR_NO"))
public class PnrStatus implements java.io.Serializable {

	private short pnrStatusId;
	private Passenger passenger;
	private short pnrNo;
	private String boardingStn;
	private String unBoardingStn;
	private Serializable dateOfJourney;
	private Serializable dateOfBooking;
	private Boolean seatConfirmed;

	public PnrStatus() {
	}

	public PnrStatus(short pnrStatusId, short pnrNo) {
		this.pnrStatusId = pnrStatusId;
		this.pnrNo = pnrNo;
	}

	public PnrStatus(short pnrStatusId, Passenger passenger, short pnrNo, String boardingStn, String unBoardingStn,
			Serializable dateOfJourney, Serializable dateOfBooking, Boolean seatConfirmed) {
		this.pnrStatusId = pnrStatusId;
		this.passenger = passenger;
		this.pnrNo = pnrNo;
		this.boardingStn = boardingStn;
		this.unBoardingStn = unBoardingStn;
		this.dateOfJourney = dateOfJourney;
		this.dateOfBooking = dateOfBooking;
		this.seatConfirmed = seatConfirmed;
	}

	@Id

	@Column(name = "PNR_STATUS_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getPnrStatusId() {
		return this.pnrStatusId;
	}

	public void setPnrStatusId(short pnrStatusId) {
		this.pnrStatusId = pnrStatusId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "PSNGR_ID")
	public Passenger getPassenger() {
		return this.passenger;
	}

	public void setPassenger(Passenger passenger) {
		this.passenger = passenger;
	}

	@Column(name = "PNR_NO", unique = true, nullable = false, precision = 4, scale = 0)
	public short getPnrNo() {
		return this.pnrNo;
	}

	public void setPnrNo(short pnrNo) {
		this.pnrNo = pnrNo;
	}

	@Column(name = "BOARDING_STN", length = 30)
	public String getBoardingStn() {
		return this.boardingStn;
	}

	public void setBoardingStn(String boardingStn) {
		this.boardingStn = boardingStn;
	}

	@Column(name = "UN_BOARDING_STN", length = 30)
	public String getUnBoardingStn() {
		return this.unBoardingStn;
	}

	public void setUnBoardingStn(String unBoardingStn) {
		this.unBoardingStn = unBoardingStn;
	}

	@Column(name = "DATE_OF_JOURNEY")
	public Serializable getDateOfJourney() {
		return this.dateOfJourney;
	}

	public void setDateOfJourney(Serializable dateOfJourney) {
		this.dateOfJourney = dateOfJourney;
	}

	@Column(name = "DATE_OF_BOOKING")
	public Serializable getDateOfBooking() {
		return this.dateOfBooking;
	}

	public void setDateOfBooking(Serializable dateOfBooking) {
		this.dateOfBooking = dateOfBooking;
	}

	@Column(name = "SEAT_CONFIRMED", precision = 1, scale = 0)
	public Boolean getSeatConfirmed() {
		return this.seatConfirmed;
	}

	public void setSeatConfirmed(Boolean seatConfirmed) {
		this.seatConfirmed = seatConfirmed;
	}

}
