package com.irc.entity;
// Generated 3 Nov, 2017 10:44:37 PM by Hibernate Tools 4.3.5.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Route generated by hbm2java
 */
@Entity
@Table(name = "ROUTE", schema = "INDIAN_RAILWAYS")
public class Route implements java.io.Serializable {

	private short routeId;
	private String routeStartingStn;
	private String routeEndingStn;
	private Set<Booking> bookings = new HashSet<Booking>(0);

	public Route() {
	}

	public Route(short routeId, String routeStartingStn, String routeEndingStn) {
		this.routeId = routeId;
		this.routeStartingStn = routeStartingStn;
		this.routeEndingStn = routeEndingStn;
	}

	public Route(short routeId, String routeStartingStn, String routeEndingStn, Set<Booking> bookings) {
		this.routeId = routeId;
		this.routeStartingStn = routeStartingStn;
		this.routeEndingStn = routeEndingStn;
		this.bookings = bookings;
	}

	@Id

	@Column(name = "ROUTE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public short getRouteId() {
		return this.routeId;
	}

	public void setRouteId(short routeId) {
		this.routeId = routeId;
	}

	@Column(name = "ROUTE_STARTING_STN", nullable = false, length = 30)
	public String getRouteStartingStn() {
		return this.routeStartingStn;
	}

	public void setRouteStartingStn(String routeStartingStn) {
		this.routeStartingStn = routeStartingStn;
	}

	@Column(name = "ROUTE_ENDING_STN", nullable = false, length = 30)
	public String getRouteEndingStn() {
		return this.routeEndingStn;
	}

	public void setRouteEndingStn(String routeEndingStn) {
		this.routeEndingStn = routeEndingStn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "route")
	public Set<Booking> getBookings() {
		return this.bookings;
	}

	public void setBookings(Set<Booking> bookings) {
		this.bookings = bookings;
	}

}
