package com.irc.entity;
// Generated 8 Oct, 2017 4:43:35 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SeatCharges generated by hbm2java
 */
@Entity
@Table(name = "SEAT_CHARGES", schema = "INDIAN_RAILWAYS")
public class SeatCharges implements java.io.Serializable {

	private short seatChargesId;
	private SeatType seatType;
	private Short charge;

	public SeatCharges() {
	}

	public SeatCharges(short seatChargesId) {
		this.seatChargesId = seatChargesId;
	}

	public SeatCharges(short seatChargesId, SeatType seatType, Short charge) {
		this.seatChargesId = seatChargesId;
		this.seatType = seatType;
		this.charge = charge;
	}

	@Id

	@Column(name = "SEAT_CHARGES_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getSeatChargesId() {
		return this.seatChargesId;
	}

	public void setSeatChargesId(short seatChargesId) {
		this.seatChargesId = seatChargesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SEAT_TYPE_ID")
	public SeatType getSeatType() {
		return this.seatType;
	}

	public void setSeatType(SeatType seatType) {
		this.seatType = seatType;
	}

	@Column(name = "CHARGE", precision = 4, scale = 0)
	public Short getCharge() {
		return this.charge;
	}

	public void setCharge(Short charge) {
		this.charge = charge;
	}

}
