package com.irc.entity;
// Generated 1 Nov, 2017 9:28:38 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * SeatType generated by hbm2java
 */
@Entity
@Table(name = "SEAT_TYPE", schema = "INDIAN_RAILWAYS")
public class SeatType implements java.io.Serializable {

	private long seatTypeId;
	private String seatType;
	private String seatTypeAcronymes;
	private short seatLimit;
	private Set<SeatCharges> seatChargeses = new HashSet<SeatCharges>(0);

	public SeatType() {
	}

	public SeatType(long seatTypeId, short seatLimit) {
		this.seatTypeId = seatTypeId;
		this.seatLimit = seatLimit;
	}

	public SeatType(long seatTypeId, String seatType, String seatTypeAcronymes, short seatLimit,
			Set<SeatCharges> seatChargeses) {
		this.seatTypeId = seatTypeId;
		this.seatType = seatType;
		this.seatTypeAcronymes = seatTypeAcronymes;
		this.seatLimit = seatLimit;
		this.seatChargeses = seatChargeses;
	}

	@Id

	@Column(name = "SEAT_TYPE_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getSeatTypeId() {
		return this.seatTypeId;
	}

	public void setSeatTypeId(long seatTypeId) {
		this.seatTypeId = seatTypeId;
	}

	@Column(name = "SEAT_TYPE", length = 40)
	public String getSeatType() {
		return this.seatType;
	}

	public void setSeatType(String seatType) {
		this.seatType = seatType;
	}

	@Column(name = "SEAT_TYPE_ACRONYMES", length = 30)
	public String getSeatTypeAcronymes() {
		return this.seatTypeAcronymes;
	}

	public void setSeatTypeAcronymes(String seatTypeAcronymes) {
		this.seatTypeAcronymes = seatTypeAcronymes;
	}

	@Column(name = "SEAT_LIMIT", nullable = false, precision = 3, scale = 0)
	public short getSeatLimit() {
		return this.seatLimit;
	}

	public void setSeatLimit(short seatLimit) {
		this.seatLimit = seatLimit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seatType")
	public Set<SeatCharges> getSeatChargeses() {
		return this.seatChargeses;
	}

	public void setSeatChargeses(Set<SeatCharges> seatChargeses) {
		this.seatChargeses = seatChargeses;
	}

}
