package com.irc.entity;
// Generated 1 Nov, 2017 9:28:38 AM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "STATE", schema = "INDIAN_RAILWAYS")
public class State implements java.io.Serializable {

	private short stateId;
	private String stateName;
	private Set<District> districts = new HashSet<District>(0);

	public State() {
	}

	public State(short stateId) {
		this.stateId = stateId;
	}

	public State(short stateId, String stateName, Set<District> districts) {
		this.stateId = stateId;
		this.stateName = stateName;
		this.districts = districts;
	}

	@Id

	@Column(name = "STATE_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getStateId() {
		return this.stateId;
	}

	public void setStateId(short stateId) {
		this.stateId = stateId;
	}

	@Column(name = "STATE_NAME", length = 30)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "state")
	public Set<District> getDistricts() {
		return this.districts;
	}

	public void setDistricts(Set<District> districts) {
		this.districts = districts;
	}

}
