package com.irc.entity;
// Generated 3 Nov, 2017 10:44:37 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "STATION", schema = "INDIAN_RAILWAYS")
public class Station implements java.io.Serializable {

	private short stationId;
	private String stationName;
	private String stationCode;
	private Set<TrainSchedule> trainSchedules = new HashSet<TrainSchedule>(0);

	public Station() {
	}

	public Station(short stationId) {
		this.stationId = stationId;
	}

	public Station(short stationId, String stationName, String stationCode, Set<TrainSchedule> trainSchedules) {
		this.stationId = stationId;
		this.stationName = stationName;
		this.stationCode = stationCode;
		this.trainSchedules = trainSchedules;
	}

	@Id

	@Column(name = "STATION_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getStationId() {
		return this.stationId;
	}

	public void setStationId(short stationId) {
		this.stationId = stationId;
	}

	@Column(name = "STATION_NAME", length = 30)
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	@Column(name = "STATION_CODE", length = 15)
	public String getStationCode() {
		return this.stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "station")
	public Set<TrainSchedule> getTrainSchedules() {
		return this.trainSchedules;
	}

	public void setTrainSchedules(Set<TrainSchedule> trainSchedules) {
		this.trainSchedules = trainSchedules;
	}

}
