package com.irc.model;
// Generated 2 Oct, 2017 8:28:59 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * StationTrains generated by hbm2java
 */
@Entity
@Table(name = "STATION_TRAINS", schema = "INDIAN_RAILWAYS")
public class StationTrains implements java.io.Serializable {

	private short stationTrainId;
	private Trains trains;
	private Station station;
	private Serializable arvlTime;
	private Serializable depTime;

	public StationTrains() {
	}

	public StationTrains(short stationTrainId) {
		this.stationTrainId = stationTrainId;
	}

	public StationTrains(short stationTrainId, Trains trains, Station station, Serializable arvlTime,
			Serializable depTime) {
		this.stationTrainId = stationTrainId;
		this.trains = trains;
		this.station = station;
		this.arvlTime = arvlTime;
		this.depTime = depTime;
	}

	@Id

	@Column(name = "STATION_TRAIN_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getStationTrainId() {
		return this.stationTrainId;
	}

	public void setStationTrainId(short stationTrainId) {
		this.stationTrainId = stationTrainId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAIN_ID")
	public Trains getTrains() {
		return this.trains;
	}

	public void setTrains(Trains trains) {
		this.trains = trains;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATION_ID")
	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	@Column(name = "ARVL_TIME")
	public Serializable getArvlTime() {
		return this.arvlTime;
	}

	public void setArvlTime(Serializable arvlTime) {
		this.arvlTime = arvlTime;
	}

	@Column(name = "DEP_TIME")
	public Serializable getDepTime() {
		return this.depTime;
	}

	public void setDepTime(Serializable depTime) {
		this.depTime = depTime;
	}

}
