package com.irc.entity;
// Generated 8 Oct, 2017 4:43:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Station generated by hbm2java
 */
@Entity
@Table(name = "STATION", schema = "INDIAN_RAILWAYS")
public class Station implements java.io.Serializable {

	private int stationId;
	private String stationName;
	private String stationCode;
	private Set<StationTrains> stationTrainses = new HashSet<StationTrains>(0);

	public Station() {
	}

	public Station(int stationId) {
		this.stationId = stationId;
	}

	public Station(int stationId, String stationName, String stationCode, Set<StationTrains> stationTrainses) {
		this.stationId = stationId;
		this.stationName = stationName;
		this.stationCode = stationCode;
		this.stationTrainses = stationTrainses;
	}

	@Id

	@Column(name = "STATION_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public int getStationId() {
		return this.stationId;
	}

	public void setStationId(int stationId2) {
		this.stationId = stationId2;
	}

	@Column(name = "STATION_NAME", length = 30)
	public String getStationName() {
		return this.stationName;
	}

	public void setStationName(String stationName) {
		this.stationName = stationName;
	}

	@Column(name = "STATION_CODE", length = 15)
	public String getStationCode() {
		return this.stationCode;
	}

	public void setStationCode(String stationCode) {
		this.stationCode = stationCode;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "station")
	public Set<StationTrains> getStationTrainses() {
		return this.stationTrainses;
	}

	public void setStationTrainses(Set<StationTrains> stationTrainses) {
		this.stationTrainses = stationTrainses;
	}

}
