package com.irc.entity;
// Generated 3 Nov, 2017 10:44:37 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TrainWeeklySchedule generated by hbm2java
 */
@Entity
@Table(name = "TRAIN_WEEKLY_SCHEDULE", schema = "INDIAN_RAILWAYS")
public class TrainWeeklySchedule implements java.io.Serializable {

	private short trnWeeklyScheId;
	private Boolean daySunday;
	private Boolean dayMonday;
	private Boolean dayTuesday;
	private Boolean dayWednesday;
	private Boolean dayThursday;
	private Boolean dayFriday;
	private Boolean daySaturday;
	private Set<TrainSchedule> trainSchedules = new HashSet<TrainSchedule>(0);
	private Set<RouteTrain> routeTrains = new HashSet<RouteTrain>(0);

	public TrainWeeklySchedule() {
	}

	public TrainWeeklySchedule(short trnWeeklyScheId) {
		this.trnWeeklyScheId = trnWeeklyScheId;
	}

	public TrainWeeklySchedule(short trnWeeklyScheId, Boolean daySunday, Boolean dayMonday, Boolean dayTuesday,
			Boolean dayWednesday, Boolean dayThursday, Boolean dayFriday, Boolean daySaturday,
			Set<TrainSchedule> trainSchedules) {
		this.trnWeeklyScheId = trnWeeklyScheId;
		this.daySunday = daySunday;
		this.dayMonday = dayMonday;
		this.dayTuesday = dayTuesday;
		this.dayWednesday = dayWednesday;
		this.dayThursday = dayThursday;
		this.dayFriday = dayFriday;
		this.daySaturday = daySaturday;
		this.trainSchedules = trainSchedules;
	}

	@Id

	@Column(name = "TRN_WEEKLY_SCHE_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getTrnWeeklyScheId() {
		return this.trnWeeklyScheId;
	}

	public void setTrnWeeklyScheId(short trnWeeklyScheId) {
		this.trnWeeklyScheId = trnWeeklyScheId;
	}

	@Column(name = "DAY_SUNDAY", precision = 1, scale = 0)
	public Boolean getDaySunday() {
		return this.daySunday;
	}

	public void setDaySunday(Boolean daySunday) {
		this.daySunday = daySunday;
	}

	@Column(name = "DAY_MONDAY", precision = 1, scale = 0)
	public Boolean getDayMonday() {
		return this.dayMonday;
	}

	public void setDayMonday(Boolean dayMonday) {
		this.dayMonday = dayMonday;
	}

	@Column(name = "DAY_TUESDAY", precision = 1, scale = 0)
	public Boolean getDayTuesday() {
		return this.dayTuesday;
	}

	public void setDayTuesday(Boolean dayTuesday) {
		this.dayTuesday = dayTuesday;
	}

	@Column(name = "DAY_WEDNESDAY", precision = 1, scale = 0)
	public Boolean getDayWednesday() {
		return this.dayWednesday;
	}

	public void setDayWednesday(Boolean dayWednesday) {
		this.dayWednesday = dayWednesday;
	}

	@Column(name = "DAY_THURSDAY", precision = 1, scale = 0)
	public Boolean getDayThursday() {
		return this.dayThursday;
	}

	public void setDayThursday(Boolean dayThursday) {
		this.dayThursday = dayThursday;
	}

	@Column(name = "DAY_FRIDAY", precision = 1, scale = 0)
	public Boolean getDayFriday() {
		return this.dayFriday;
	}

	public void setDayFriday(Boolean dayFriday) {
		this.dayFriday = dayFriday;
	}

	@Column(name = "DAY_SATURDAY", precision = 1, scale = 0)
	public Boolean getDaySaturday() {
		return this.daySaturday;
	}

	public void setDaySaturday(Boolean daySaturday) {
		this.daySaturday = daySaturday;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trainWeeklySchedule")
	public Set<TrainSchedule> getTrainSchedules() {
		return this.trainSchedules;
	}

	public void setTrainSchedules(Set<TrainSchedule> trainSchedules) {
		this.trainSchedules = trainSchedules;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trainWeeklySchedule")
	public Set<RouteTrain> getRouteTrains() {
		return this.routeTrains;
	}

	public void setRouteTrains(Set<RouteTrain> routeTrains) {
		this.routeTrains = routeTrains;
	}

}
