package com.irc.entity;
// Generated 8 Oct, 2017 4:43:35 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Trains generated by hbm2java
 */
@Entity
@Table(name = "TRAINS", schema = "INDIAN_RAILWAYS")
public class Trains implements java.io.Serializable {

	private int trainId;
	private String trainModel;
	private String trainAvgSpeed;
	private String trainSourceStation;
	private String trainDestinationStation;
	private String trainName;
	private Set<TrainStatus> trainStatuses = new HashSet<TrainStatus>(0);
	private Set<TrainCoachSeatBooking> trainCoachSeatBookings = new HashSet<TrainCoachSeatBooking>(0);
	private Set<StationTrains> stationTrainses = new HashSet<StationTrains>(0);

	public Trains() {
	}

	public Trains(short trainId) {
		this.trainId = trainId;
	}

	public Trains(short trainId, String trainModel, String trainAvgSpeed, String trainSourceStation,
			String trainDestinationStation, String trainName, Set<TrainStatus> trainStatuses,
			Set<TrainCoachSeatBooking> trainCoachSeatBookings, Set<StationTrains> stationTrainses) {
		this.trainId = trainId;
		this.trainModel = trainModel;
		this.trainAvgSpeed = trainAvgSpeed;
		this.trainSourceStation = trainSourceStation;
		this.trainDestinationStation = trainDestinationStation;
		this.trainName = trainName;
		this.trainStatuses = trainStatuses;
		this.trainCoachSeatBookings = trainCoachSeatBookings;
		this.stationTrainses = stationTrainses;
	}

	@Id

	@Column(name = "TRAIN_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public int getTrainId() {
		return this.trainId;
	}

	public void setTrainId(int trainId2) {
		this.trainId = trainId2;
	}

	@Column(name = "TRAIN_MODEL", length = 30)
	public String getTrainModel() {
		return this.trainModel;
	}

	public void setTrainModel(String trainModel) {
		this.trainModel = trainModel;
	}

	@Column(name = "TRAIN_AVG_SPEED", length = 30)
	public String getTrainAvgSpeed() {
		return this.trainAvgSpeed;
	}

	public void setTrainAvgSpeed(String trainAvgSpeed) {
		this.trainAvgSpeed = trainAvgSpeed;
	}

	@Column(name = "TRAIN_SOURCE_STATION", length = 30)
	public String getTrainSourceStation() {
		return this.trainSourceStation;
	}

	public void setTrainSourceStation(String trainSourceStation) {
		this.trainSourceStation = trainSourceStation;
	}

	@Column(name = "TRAIN_DESTINATION_STATION", length = 30)
	public String getTrainDestinationStation() {
		return this.trainDestinationStation;
	}

	public void setTrainDestinationStation(String trainDestinationStation) {
		this.trainDestinationStation = trainDestinationStation;
	}

	@Column(name = "TRAIN_NAME", length = 30)
	public String getTrainName() {
		return this.trainName;
	}

	public void setTrainName(String trainName) {
		this.trainName = trainName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trains")
	public Set<TrainStatus> getTrainStatuses() {
		return this.trainStatuses;
	}

	public void setTrainStatuses(Set<TrainStatus> trainStatuses) {
		this.trainStatuses = trainStatuses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trains")
	public Set<TrainCoachSeatBooking> getTrainCoachSeatBookings() {
		return this.trainCoachSeatBookings;
	}

	public void setTrainCoachSeatBookings(Set<TrainCoachSeatBooking> trainCoachSeatBookings) {
		this.trainCoachSeatBookings = trainCoachSeatBookings;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "trains")
	public Set<StationTrains> getStationTrainses() {
		return this.stationTrainses;
	}

	public void setStationTrainses(Set<StationTrains> stationTrainses) {
		this.stationTrainses = stationTrainses;
	}

}
