package com.irc.model;
// Generated 2 Oct, 2017 8:28:59 PM by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TrainCoaches generated by hbm2java
 */
@Entity
@Table(name = "TRAIN_COACHES", schema = "INDIAN_RAILWAYS")
public class TrainCoaches implements java.io.Serializable {

	private short trainCoachesId;
	private Coach coach;
	private Integer trainId;

	public TrainCoaches() {
	}

	public TrainCoaches(short trainCoachesId) {
		this.trainCoachesId = trainCoachesId;
	}

	public TrainCoaches(short trainCoachesId, Coach coach, Integer trainId) {
		this.trainCoachesId = trainCoachesId;
		this.coach = coach;
		this.trainId = trainId;
	}

	@Id

	@Column(name = "TRAIN_COACHES_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getTrainCoachesId() {
		return this.trainCoachesId;
	}

	public void setTrainCoachesId(short trainCoachesId) {
		this.trainCoachesId = trainCoachesId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "COACH_ID")
	public Coach getCoach() {
		return this.coach;
	}

	public void setCoach(Coach coach) {
		this.coach = coach;
	}

	@Column(name = "TRAIN_ID", precision = 5, scale = 0)
	public Integer getTrainId() {
		return this.trainId;
	}

	public void setTrainId(Integer trainId) {
		this.trainId = trainId;
	}

}
