package com.irc.entity;
// Generated 3 Nov, 2017 10:44:37 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TrainSchedule generated by hbm2java
 */
@Entity
@Table(name = "TRAIN_SCHEDULE", schema = "INDIAN_RAILWAYS")
public class TrainSchedule implements java.io.Serializable {

	private int trainScheId;
	private Train train;
	private Station station;
	private TrainWeeklySchedule trainWeeklySchedule;
	private Serializable arrvlTime;
	private Serializable deprTime;
	private String dayOfJourney;

	public TrainSchedule() {
	}

	public TrainSchedule(int trainScheId) {
		this.trainScheId = trainScheId;
	}

	public TrainSchedule(int trainScheId, Train train, Station station, TrainWeeklySchedule trainWeeklySchedule,
			Serializable arrvlTime, Serializable deprTime, String dayOfJourney) {
		this.trainScheId = trainScheId;
		this.train = train;
		this.station = station;
		this.trainWeeklySchedule = trainWeeklySchedule;
		this.arrvlTime = arrvlTime;
		this.deprTime = deprTime;
		this.dayOfJourney = dayOfJourney;
	}

	@Id

	@Column(name = "TRAIN_SCHE_ID", unique = true, nullable = false, precision = 6, scale = 0)
	public int getTrainScheId() {
		return this.trainScheId;
	}

	public void setTrainScheId(int trainScheId) {
		this.trainScheId = trainScheId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAIN_ID")
	public Train getTrain() {
		return this.train;
	}

	public void setTrain(Train train) {
		this.train = train;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "STATION_ID")
	public Station getStation() {
		return this.station;
	}

	public void setStation(Station station) {
		this.station = station;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRN_WEEKLY_SCHE_ID")
	public TrainWeeklySchedule getTrainWeeklySchedule() {
		return this.trainWeeklySchedule;
	}

	public void setTrainWeeklySchedule(TrainWeeklySchedule trainWeeklySchedule) {
		this.trainWeeklySchedule = trainWeeklySchedule;
	}

	@Column(name = "ARRVL_TIME")
	public Serializable getArrvlTime() {
		return this.arrvlTime;
	}

	public void setArrvlTime(Serializable arrvlTime) {
		this.arrvlTime = arrvlTime;
	}

	@Column(name = "DEPR_TIME")
	public Serializable getDeprTime() {
		return this.deprTime;
	}

	public void setDeprTime(Serializable deprTime) {
		this.deprTime = deprTime;
	}

	@Column(name = "DAY_OF_JOURNEY", length = 6)
	public String getDayOfJourney() {
		return this.dayOfJourney;
	}

	public void setDayOfJourney(String dayOfJourney) {
		this.dayOfJourney = dayOfJourney;
	}

}
