package com.irc.entity;
// Generated 8 Oct, 2017 4:43:35 PM by Hibernate Tools 4.3.5.Final

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TrainStatus generated by hbm2java
 */
@Entity
@Table(name = "TRAIN_STATUS", schema = "INDIAN_RAILWAYS")
public class TrainStatus implements java.io.Serializable {

	private short trainStatusId;
	private Trains trains;
	private Serializable dateOfStatus;
	private String arrivalStnNm;
	private Serializable arrivalTime;
	private String departureStnNm;
	private Serializable departureTime;

	public TrainStatus() {
	}

	public TrainStatus(short trainStatusId) {
		this.trainStatusId = trainStatusId;
	}

	public TrainStatus(short trainStatusId, Trains trains, Serializable dateOfStatus, String arrivalStnNm,
			Serializable arrivalTime, String departureStnNm, Serializable departureTime) {
		this.trainStatusId = trainStatusId;
		this.trains = trains;
		this.dateOfStatus = dateOfStatus;
		this.arrivalStnNm = arrivalStnNm;
		this.arrivalTime = arrivalTime;
		this.departureStnNm = departureStnNm;
		this.departureTime = departureTime;
	}

	@Id

	@Column(name = "TRAIN_STATUS_ID", unique = true, nullable = false, precision = 4, scale = 0)
	public short getTrainStatusId() {
		return this.trainStatusId;
	}

	public void setTrainStatusId(short trainStatusId) {
		this.trainStatusId = trainStatusId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "TRAIN_ID")
	public Trains getTrains() {
		return this.trains;
	}

	public void setTrains(Trains trains) {
		this.trains = trains;
	}

	@Column(name = "DATE_OF_STATUS")
	public Serializable getDateOfStatus() {
		return this.dateOfStatus;
	}

	public void setDateOfStatus(Serializable dateOfStatus) {
		this.dateOfStatus = dateOfStatus;
	}

	@Column(name = "ARRIVAL_STN_NM", length = 30)
	public String getArrivalStnNm() {
		return this.arrivalStnNm;
	}

	public void setArrivalStnNm(String arrivalStnNm) {
		this.arrivalStnNm = arrivalStnNm;
	}

	@Column(name = "ARRIVAL_TIME")
	public Serializable getArrivalTime() {
		return this.arrivalTime;
	}

	public void setArrivalTime(Serializable arrivalTime) {
		this.arrivalTime = arrivalTime;
	}

	@Column(name = "DEPARTURE_STN_NM", length = 30)
	public String getDepartureStnNm() {
		return this.departureStnNm;
	}

	public void setDepartureStnNm(String departureStnNm) {
		this.departureStnNm = departureStnNm;
	}

	@Column(name = "DEPARTURE_TIME")
	public Serializable getDepartureTime() {
		return this.departureTime;
	}

	public void setDepartureTime(Serializable departureTime) {
		this.departureTime = departureTime;
	}

}
